INSERT INTO APP.LISTA (ID, "NAME", ALBUM_NUMBER) 
	VALUES (1, 'Marek', 4521);
INSERT INTO APP.LISTA (ID, "NAME", ALBUM_NUMBER) 
	VALUES (2, 'Adam', 1111);
INSERT INTO APP.LISTA (ID, "NAME", ALBUM_NUMBER) 
	VALUES (3, 'Ewa', 2222);
INSERT INTO APP.LISTA (ID, "NAME", ALBUM_NUMBER) 
	VALUES (4, 'Karol', 3333);
INSERT INTO APP.LISTA (ID, "NAME", ALBUM_NUMBER) 
	VALUES (5, 'Julia', 4444);
INSERT INTO APP.LISTA (ID, "NAME", ALBUM_NUMBER) 
	VALUES (6, 'Tomasz', 5555);
INSERT INTO APP.LISTA (ID, "NAME", ALBUM_NUMBER) 
	VALUES (7, 'Alicja', 6666);
INSERT INTO APP.LISTA (ID, "NAME", ALBUM_NUMBER) 
	VALUES (8, 'Marta', 7777);
INSERT INTO APP.LISTA (ID, "NAME", ALBUM_NUMBER) 
	VALUES (9, 'Krzysztof', 8888);
INSERT INTO APP.LISTA (ID, "NAME", ALBUM_NUMBER) 
	VALUES (10, 'Nadia', 9999);
INSERT INTO APP.LISTA (ID, "NAME", ALBUM_NUMBER) 
	VALUES (11, 'Oliwia', 1234);
